### ISSUE TITLE
Запустить на файле большего размера

### ISSUE THREAD

**Issue by egor1989** [ArcticTower/Ing#2]
https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-big.7z

**Comment by ArcticTower** [comment]
запущен на lng-big.csv. Пришлось поманять под задачу алгоритм проверки валидности строки. В дальнейшем можно добавить запрос регулярного выражения при запуске программы.
Время выполнения 584 секунды, что долго. Я бы мог добавить многопоточность, но мой ноутбук уже выходит в турбобуст и слишком греется, поэтому нет условий для выполнения задачи.

**Comment by mad** [comment]
Число групп неправильное для обоих файлов

Большой файл должен обрабатываться даже на ноуте. На Intel Core i5 4210M (2x2.60 ГГц), RAM 8 ГБ считается не больше 30 секунд

**Comment by ArcticTower** [comment]
@mad изменил алгоритм, время работы сократилось до 25-28 секунд на большом файле, 4-6 в маленьком. Изменил readme (добавил новые данные). Для проверки значений, которые разделены ";" в строке использовал регулярные выражения ^"\d+"$ и ^\"\\d+\\.\\d+\"$. Пропускал строки с 1 элементом. Группы отсортировал по количеству строк. Делал немного долго из-за учёбы.

**Comment by ArcticTower** [comment]
сократил до 20-25 для большого
